
export interface ActionItem {
  id: number;
  task: string;
  owner: string;
  dueDate: string;
}

export interface MeetingData {
  title: string;
  date: string;
  time: string;
  location: string;
  attendees: string;
  absentees: string;
  agenda: string;
  discussion: string;
  actionItems: ActionItem[];
}

const formatList = (input: string): string => {
  return input.split('\n').map(item => item.trim() ? `- ${item.trim()}` : '').filter(Boolean).join('\n');
};

export const generateMarkdown = (data: MeetingData): string => {
  const { title, date, time, location, attendees, absentees, agenda, discussion, actionItems } = data;

  const formattedDate = date ? new Date(date + 'T00:00:00').toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) : 'N/A';
  const formattedTime = time || 'N/A';

  const actionItemsTable = actionItems.length > 0
    ? `| Action Item | Owner | Due Date |\n|---|---|---|\n` +
      actionItems.map(item => `| ${item.task || ' '} | ${item.owner || ' '} | ${item.dueDate || ' '} |`).join('\n')
    : 'No action items were assigned.';

  return `
# Meeting Minutes: ${title || 'Untitled Meeting'}

---

**Date:** ${formattedDate}  
**Time:** ${formattedTime}  
**Location:** ${location || 'N/A'}  

---

## Attendees

${attendees ? formatList(attendees) : 'No attendees listed.'}

## Absentees

${absentees ? formatList(absentees) : 'No absentees listed.'}

---

## Agenda

${agenda ? formatList(agenda) : 'No agenda items provided.'}

---

## Discussion & Decisions

${discussion || 'No discussion notes provided.'}

---

## Action Items

${actionItemsTable}

---

*Minutes generated by AI Meeting Minutes Generator.*
  `.trim();
};
